<?php
/**
 * ApplicationUpdateExistingLoanDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Onboarding
 *
 * The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationUpdateExistingLoanDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicationUpdateExistingLoanDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationUpdateExistingLoanDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationUpdateExistingLoanDetails"
     */
    public function testApplicationUpdateExistingLoanDetails()
    {
    }

    /**
     * Test attribute "loan_type"
     */
    public function testPropertyLoanType()
    {
    }

    /**
     * Test attribute "other_debt_obligation_type"
     */
    public function testPropertyOtherDebtObligationType()
    {
    }

    /**
     * Test attribute "monthly_installment_amount"
     */
    public function testPropertyMonthlyInstallmentAmount()
    {
    }

    /**
     * Test attribute "outstanding_balance_amount"
     */
    public function testPropertyOutstandingBalanceAmount()
    {
    }

    /**
     * Test attribute "debt_ownership"
     */
    public function testPropertyDebtOwnership()
    {
    }

    /**
     * Test attribute "lender_name"
     */
    public function testPropertyLenderName()
    {
    }
}
