<?php
/**
 * ApplicantUpdateApplicantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Onboarding
 *
 * The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicantUpdateApplicantTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicantUpdateApplicant
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicantUpdateApplicantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicantUpdateApplicant"
     */
    public function testApplicantUpdateApplicant()
    {
    }

    /**
     * Test attribute "applicant_type"
     */
    public function testPropertyApplicantType()
    {
    }

    /**
     * Test attribute "mother_maiden_name"
     */
    public function testPropertyMotherMaidenName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "demographics"
     */
    public function testPropertyDemographics()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "financial_information"
     */
    public function testPropertyFinancialInformation()
    {
    }

    /**
     * Test attribute "employment_details"
     */
    public function testPropertyEmploymentDetails()
    {
    }

    /**
     * Test attribute "identification_document_details"
     */
    public function testPropertyIdentificationDocumentDetails()
    {
    }

    /**
     * Test attribute "additional_data"
     */
    public function testPropertyAdditionalData()
    {
    }

    /**
     * Test attribute "partner_customer_details"
     */
    public function testPropertyPartnerCustomerDetails()
    {
    }

    /**
     * Test attribute "consent_details"
     */
    public function testPropertyConsentDetails()
    {
    }

    /**
     * Test attribute "kyc_information"
     */
    public function testPropertyKycInformation()
    {
    }

    /**
     * Test attribute "contact_consent"
     */
    public function testPropertyContactConsent()
    {
    }
}
