# coding: utf-8

"""
    Accounts

    The Accounts API allows you to retrieve account and transaction data for Citi Customers who have authorized your app. In most cases, you'll want to request a summary of all accounts first, which will return basic account information and accountIds. Once you have this information, you can request additional account details and/or transactions.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'loan_reference_id': 'str',
        'installment_amount': 'float',
        'principal_amount': 'float',
        'installment_interest_amount': 'float',
        'initial_interest_amount': 'float',
        'statement_unpaid_balance_amount': 'float',
        'statement_minimum_due_balance_amount': 'float',
        'statement_payment_due_date': 'date'
    }

    attribute_map = {
        'loan_reference_id': 'loanReferenceId',
        'installment_amount': 'installmentAmount',
        'principal_amount': 'principalAmount',
        'installment_interest_amount': 'installmentInterestAmount',
        'initial_interest_amount': 'initialInterestAmount',
        'statement_unpaid_balance_amount': 'statementUnpaidBalanceAmount',
        'statement_minimum_due_balance_amount': 'statementMinimumDueBalanceAmount',
        'statement_payment_due_date': 'statementPaymentDueDate'
    }

    def __init__(self, loan_reference_id=None, installment_amount=None, principal_amount=None, installment_interest_amount=None, initial_interest_amount=None, statement_unpaid_balance_amount=None, statement_minimum_due_balance_amount=None, statement_payment_due_date=None):  # noqa: E501
        """RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse - a model defined in Swagger"""  # noqa: E501
        self._loan_reference_id = None
        self._installment_amount = None
        self._principal_amount = None
        self._installment_interest_amount = None
        self._initial_interest_amount = None
        self._statement_unpaid_balance_amount = None
        self._statement_minimum_due_balance_amount = None
        self._statement_payment_due_date = None
        self.discriminator = None
        self.loan_reference_id = loan_reference_id
        if installment_amount is not None:
            self.installment_amount = installment_amount
        if principal_amount is not None:
            self.principal_amount = principal_amount
        if installment_interest_amount is not None:
            self.installment_interest_amount = installment_interest_amount
        if initial_interest_amount is not None:
            self.initial_interest_amount = initial_interest_amount
        if statement_unpaid_balance_amount is not None:
            self.statement_unpaid_balance_amount = statement_unpaid_balance_amount
        if statement_minimum_due_balance_amount is not None:
            self.statement_minimum_due_balance_amount = statement_minimum_due_balance_amount
        if statement_payment_due_date is not None:
            self.statement_payment_due_date = statement_payment_due_date

    @property
    def loan_reference_id(self):
        """Gets the loan_reference_id of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        The unique  reference Id used to identify this Loan from all the other Loans  # noqa: E501

        :return: The loan_reference_id of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: str
        """
        return self._loan_reference_id

    @loan_reference_id.setter
    def loan_reference_id(self, loan_reference_id):
        """Sets the loan_reference_id of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        The unique  reference Id used to identify this Loan from all the other Loans  # noqa: E501

        :param loan_reference_id: The loan_reference_id of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: str
        """
        if loan_reference_id is None:
            raise ValueError("Invalid value for `loan_reference_id`, must not be `None`")  # noqa: E501

        self._loan_reference_id = loan_reference_id

    @property
    def installment_amount(self):
        """Gets the installment_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        Installment amount to be paid by customer in order to repay the loan.  # noqa: E501

        :return: The installment_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._installment_amount

    @installment_amount.setter
    def installment_amount(self, installment_amount):
        """Sets the installment_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        Installment amount to be paid by customer in order to repay the loan.  # noqa: E501

        :param installment_amount: The installment_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._installment_amount = installment_amount

    @property
    def principal_amount(self):
        """Gets the principal_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        The portion of the Principal Amount Paid for the loan.  # noqa: E501

        :return: The principal_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._principal_amount

    @principal_amount.setter
    def principal_amount(self, principal_amount):
        """Sets the principal_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        The portion of the Principal Amount Paid for the loan.  # noqa: E501

        :param principal_amount: The principal_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._principal_amount = principal_amount

    @property
    def installment_interest_amount(self):
        """Gets the installment_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        The interest amount to be paid as installment.  # noqa: E501

        :return: The installment_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._installment_interest_amount

    @installment_interest_amount.setter
    def installment_interest_amount(self, installment_interest_amount):
        """Sets the installment_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        The interest amount to be paid as installment.  # noqa: E501

        :param installment_interest_amount: The installment_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._installment_interest_amount = installment_interest_amount

    @property
    def initial_interest_amount(self):
        """Gets the initial_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        Initial interest amount charged to customer from the epp booking date to the first installment start date  # noqa: E501

        :return: The initial_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._initial_interest_amount

    @initial_interest_amount.setter
    def initial_interest_amount(self, initial_interest_amount):
        """Sets the initial_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        Initial interest amount charged to customer from the epp booking date to the first installment start date  # noqa: E501

        :param initial_interest_amount: The initial_interest_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._initial_interest_amount = initial_interest_amount

    @property
    def statement_unpaid_balance_amount(self):
        """Gets the statement_unpaid_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        This field indicates the remaining statement balance amount that remains due and payable.  # noqa: E501

        :return: The statement_unpaid_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._statement_unpaid_balance_amount

    @statement_unpaid_balance_amount.setter
    def statement_unpaid_balance_amount(self, statement_unpaid_balance_amount):
        """Sets the statement_unpaid_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        This field indicates the remaining statement balance amount that remains due and payable.  # noqa: E501

        :param statement_unpaid_balance_amount: The statement_unpaid_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._statement_unpaid_balance_amount = statement_unpaid_balance_amount

    @property
    def statement_minimum_due_balance_amount(self):
        """Gets the statement_minimum_due_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        Minimum due amount for a payment cycle  # noqa: E501

        :return: The statement_minimum_due_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: float
        """
        return self._statement_minimum_due_balance_amount

    @statement_minimum_due_balance_amount.setter
    def statement_minimum_due_balance_amount(self, statement_minimum_due_balance_amount):
        """Sets the statement_minimum_due_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        Minimum due amount for a payment cycle  # noqa: E501

        :param statement_minimum_due_balance_amount: The statement_minimum_due_balance_amount of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: float
        """

        self._statement_minimum_due_balance_amount = statement_minimum_due_balance_amount

    @property
    def statement_payment_due_date(self):
        """Gets the statement_payment_due_date of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501

        Next payment due date in ISO 8601 date format YYYY-MM-DD  # noqa: E501

        :return: The statement_payment_due_date of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :rtype: date
        """
        return self._statement_payment_due_date

    @statement_payment_due_date.setter
    def statement_payment_due_date(self, statement_payment_due_date):
        """Sets the statement_payment_due_date of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.

        Next payment due date in ISO 8601 date format YYYY-MM-DD  # noqa: E501

        :param statement_payment_due_date: The statement_payment_due_date of this RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse.  # noqa: E501
        :type: date
        """

        self._statement_payment_due_date = statement_payment_due_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RetrieveCreditChargeCardFulfillmentArrangementCreditPlanOffersEppBookingsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
