/* 
 * Cards
 *
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LinkedAccountDetails
    /// </summary>
    [DataContract]
        public partial class LinkedAccountDetails :  IEquatable<LinkedAccountDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedAccountDetails" /> class.
        /// </summary>
        /// <param name="accountId">The customer account identifier of the linked account in encrypted format.</param>
        /// <param name="displayAccountNumber">This is the masked account number of the linked account that can be displayed to the customer.</param>
        /// <param name="currencyCode">Currency code of the linked account in ISO 4217 format..</param>
        /// <param name="accountBalance">Current Balance of the linked account..</param>
        public LinkedAccountDetails(string accountId = default(string), string displayAccountNumber = default(string), string currencyCode = default(string), double? accountBalance = default(double?))
        {
            this.AccountId = accountId;
            this.DisplayAccountNumber = displayAccountNumber;
            this.CurrencyCode = currencyCode;
            this.AccountBalance = accountBalance;
        }
        
        /// <summary>
        /// The customer account identifier of the linked account in encrypted format
        /// </summary>
        /// <value>The customer account identifier of the linked account in encrypted format</value>
        [DataMember(Name="accountId", EmitDefaultValue=false)]
        public string AccountId { get; set; }

        /// <summary>
        /// This is the masked account number of the linked account that can be displayed to the customer
        /// </summary>
        /// <value>This is the masked account number of the linked account that can be displayed to the customer</value>
        [DataMember(Name="displayAccountNumber", EmitDefaultValue=false)]
        public string DisplayAccountNumber { get; set; }

        /// <summary>
        /// Currency code of the linked account in ISO 4217 format.
        /// </summary>
        /// <value>Currency code of the linked account in ISO 4217 format.</value>
        [DataMember(Name="currencyCode", EmitDefaultValue=false)]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Current Balance of the linked account.
        /// </summary>
        /// <value>Current Balance of the linked account.</value>
        [DataMember(Name="accountBalance", EmitDefaultValue=false)]
        public double? AccountBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LinkedAccountDetails {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  DisplayAccountNumber: ").Append(DisplayAccountNumber).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  AccountBalance: ").Append(AccountBalance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LinkedAccountDetails);
        }

        /// <summary>
        /// Returns true if LinkedAccountDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of LinkedAccountDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LinkedAccountDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AccountId == input.AccountId ||
                    (this.AccountId != null &&
                    this.AccountId.Equals(input.AccountId))
                ) && 
                (
                    this.DisplayAccountNumber == input.DisplayAccountNumber ||
                    (this.DisplayAccountNumber != null &&
                    this.DisplayAccountNumber.Equals(input.DisplayAccountNumber))
                ) && 
                (
                    this.CurrencyCode == input.CurrencyCode ||
                    (this.CurrencyCode != null &&
                    this.CurrencyCode.Equals(input.CurrencyCode))
                ) && 
                (
                    this.AccountBalance == input.AccountBalance ||
                    (this.AccountBalance != null &&
                    this.AccountBalance.Equals(input.AccountBalance))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountId != null)
                    hashCode = hashCode * 59 + this.AccountId.GetHashCode();
                if (this.DisplayAccountNumber != null)
                    hashCode = hashCode * 59 + this.DisplayAccountNumber.GetHashCode();
                if (this.CurrencyCode != null)
                    hashCode = hashCode * 59 + this.CurrencyCode.GetHashCode();
                if (this.AccountBalance != null)
                    hashCode = hashCode * 59 + this.AccountBalance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
