/* 
 * Cards
 *
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Loan
    /// </summary>
    [DataContract]
        public partial class Loan :  IEquatable<Loan>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Loan" /> class.
        /// </summary>
        /// <param name="loanReferenceId">Unique refrence number associated with the loan. (required).</param>
        public Loan(string loanReferenceId = default(string))
        {
            // to ensure "loanReferenceId" is required (not null)
            if (loanReferenceId == null)
            {
                throw new InvalidDataException("loanReferenceId is a required property for Loan and cannot be null");
            }
            else
            {
                this.LoanReferenceId = loanReferenceId;
            }
        }
        
        /// <summary>
        /// Unique refrence number associated with the loan.
        /// </summary>
        /// <value>Unique refrence number associated with the loan.</value>
        [DataMember(Name="loanReferenceId", EmitDefaultValue=false)]
        public string LoanReferenceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Loan {\n");
            sb.Append("  LoanReferenceId: ").Append(LoanReferenceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Loan);
        }

        /// <summary>
        /// Returns true if Loan instances are equal
        /// </summary>
        /// <param name="input">Instance of Loan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Loan input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanReferenceId == input.LoanReferenceId ||
                    (this.LoanReferenceId != null &&
                    this.LoanReferenceId.Equals(input.LoanReferenceId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanReferenceId != null)
                    hashCode = hashCode * 59 + this.LoanReferenceId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
