/* 
 * Onboarding
 *
 * The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ApplicationInquiryExistingLoanDetails
    /// </summary>
    [DataContract]
        public partial class ApplicationInquiryExistingLoanDetails :  IEquatable<ApplicationInquiryExistingLoanDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationInquiryExistingLoanDetails" /> class.
        /// </summary>
        /// <param name="loanType">Loan Type.This is a reference data field. Please use /v1/apac/utilities/referenceData/{loanType} resource to get valid value of this field with description. You can use loanType field name as the referenceCode parameter to retrieve the values..</param>
        /// <param name="monthlyInstallmentAmount">Monthly repayment amount.</param>
        /// <param name="outstandingBalanceAmount">Balance Owing.</param>
        public ApplicationInquiryExistingLoanDetails(string loanType = default(string), double? monthlyInstallmentAmount = default(double?), double? outstandingBalanceAmount = default(double?))
        {
            this.LoanType = loanType;
            this.MonthlyInstallmentAmount = monthlyInstallmentAmount;
            this.OutstandingBalanceAmount = outstandingBalanceAmount;
        }
        
        /// <summary>
        /// Loan Type.This is a reference data field. Please use /v1/apac/utilities/referenceData/{loanType} resource to get valid value of this field with description. You can use loanType field name as the referenceCode parameter to retrieve the values.
        /// </summary>
        /// <value>Loan Type.This is a reference data field. Please use /v1/apac/utilities/referenceData/{loanType} resource to get valid value of this field with description. You can use loanType field name as the referenceCode parameter to retrieve the values.</value>
        [DataMember(Name="loanType", EmitDefaultValue=false)]
        public string LoanType { get; set; }

        /// <summary>
        /// Monthly repayment amount
        /// </summary>
        /// <value>Monthly repayment amount</value>
        [DataMember(Name="monthlyInstallmentAmount", EmitDefaultValue=false)]
        public double? MonthlyInstallmentAmount { get; set; }

        /// <summary>
        /// Balance Owing
        /// </summary>
        /// <value>Balance Owing</value>
        [DataMember(Name="outstandingBalanceAmount", EmitDefaultValue=false)]
        public double? OutstandingBalanceAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApplicationInquiryExistingLoanDetails {\n");
            sb.Append("  LoanType: ").Append(LoanType).Append("\n");
            sb.Append("  MonthlyInstallmentAmount: ").Append(MonthlyInstallmentAmount).Append("\n");
            sb.Append("  OutstandingBalanceAmount: ").Append(OutstandingBalanceAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApplicationInquiryExistingLoanDetails);
        }

        /// <summary>
        /// Returns true if ApplicationInquiryExistingLoanDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ApplicationInquiryExistingLoanDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationInquiryExistingLoanDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanType == input.LoanType ||
                    (this.LoanType != null &&
                    this.LoanType.Equals(input.LoanType))
                ) && 
                (
                    this.MonthlyInstallmentAmount == input.MonthlyInstallmentAmount ||
                    (this.MonthlyInstallmentAmount != null &&
                    this.MonthlyInstallmentAmount.Equals(input.MonthlyInstallmentAmount))
                ) && 
                (
                    this.OutstandingBalanceAmount == input.OutstandingBalanceAmount ||
                    (this.OutstandingBalanceAmount != null &&
                    this.OutstandingBalanceAmount.Equals(input.OutstandingBalanceAmount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanType != null)
                    hashCode = hashCode * 59 + this.LoanType.GetHashCode();
                if (this.MonthlyInstallmentAmount != null)
                    hashCode = hashCode * 59 + this.MonthlyInstallmentAmount.GetHashCode();
                if (this.OutstandingBalanceAmount != null)
                    hashCode = hashCode * 59 + this.OutstandingBalanceAmount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
