# coding: utf-8

"""
    Cards

    The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataFeesCharges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fee_charge_detail': 'list[DataFeesChargesFeeChargeDetail]'
    }

    attribute_map = {
        'fee_charge_detail': 'fee_charge_detail'
    }

    def __init__(self, fee_charge_detail=None):  # noqa: E501
        """DataFeesCharges - a model defined in Swagger"""  # noqa: E501
        self._fee_charge_detail = None
        self.discriminator = None
        if fee_charge_detail is not None:
            self.fee_charge_detail = fee_charge_detail

    @property
    def fee_charge_detail(self):
        """Gets the fee_charge_detail of this DataFeesCharges.  # noqa: E501


        :return: The fee_charge_detail of this DataFeesCharges.  # noqa: E501
        :rtype: list[DataFeesChargesFeeChargeDetail]
        """
        return self._fee_charge_detail

    @fee_charge_detail.setter
    def fee_charge_detail(self, fee_charge_detail):
        """Sets the fee_charge_detail of this DataFeesCharges.


        :param fee_charge_detail: The fee_charge_detail of this DataFeesCharges.  # noqa: E501
        :type: list[DataFeesChargesFeeChargeDetail]
        """

        self._fee_charge_detail = fee_charge_detail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataFeesCharges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFeesCharges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
