/*
 * Cards
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BeneficiaryDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-14T16:43:49.245466Z[Etc/UTC]")
public class BeneficiaryDetail {
  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("beneficiaryBankCode")
  private String beneficiaryBankCode = null;

  @SerializedName("beneficiaryBranchCode")
  private String beneficiaryBranchCode = null;

  @SerializedName("bankName")
  private String bankName = null;

  @SerializedName("beneficiaryName")
  private String beneficiaryName = null;

  public BeneficiaryDetail accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Customers Account Number with the Bank
   * @return accountNumber
  **/
  @Schema(example = "5269013309917800", description = "Customers Account Number with the Bank")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public BeneficiaryDetail beneficiaryBankCode(String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
    return this;
  }

   /**
   * Bank Code of the Beneficiary Account Number
   * @return beneficiaryBankCode
  **/
  @Schema(example = "ABC", description = "Bank Code of the Beneficiary Account Number")
  public String getBeneficiaryBankCode() {
    return beneficiaryBankCode;
  }

  public void setBeneficiaryBankCode(String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
  }

  public BeneficiaryDetail beneficiaryBranchCode(String beneficiaryBranchCode) {
    this.beneficiaryBranchCode = beneficiaryBranchCode;
    return this;
  }

   /**
   * Branch Code of the Beneficiary Account Number
   * @return beneficiaryBranchCode
  **/
  @Schema(example = "1234", description = "Branch Code of the Beneficiary Account Number")
  public String getBeneficiaryBranchCode() {
    return beneficiaryBranchCode;
  }

  public void setBeneficiaryBranchCode(String beneficiaryBranchCode) {
    this.beneficiaryBranchCode = beneficiaryBranchCode;
  }

  public BeneficiaryDetail bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Name of the bank where the branch is associated
   * @return bankName
  **/
  @Schema(example = "ANZ BANK", description = "Name of the bank where the branch is associated")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public BeneficiaryDetail beneficiaryName(String beneficiaryName) {
    this.beneficiaryName = beneficiaryName;
    return this;
  }

   /**
   * Beneficiary Name
   * @return beneficiaryName
  **/
  @Schema(example = "TAN SHAN SHAN", description = "Beneficiary Name")
  public String getBeneficiaryName() {
    return beneficiaryName;
  }

  public void setBeneficiaryName(String beneficiaryName) {
    this.beneficiaryName = beneficiaryName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeneficiaryDetail beneficiaryDetail = (BeneficiaryDetail) o;
    return Objects.equals(this.accountNumber, beneficiaryDetail.accountNumber) &&
        Objects.equals(this.beneficiaryBankCode, beneficiaryDetail.beneficiaryBankCode) &&
        Objects.equals(this.beneficiaryBranchCode, beneficiaryDetail.beneficiaryBranchCode) &&
        Objects.equals(this.bankName, beneficiaryDetail.bankName) &&
        Objects.equals(this.beneficiaryName, beneficiaryDetail.beneficiaryName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, beneficiaryBankCode, beneficiaryBranchCode, bankName, beneficiaryName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeneficiaryDetail {\n");
    
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    beneficiaryBankCode: ").append(toIndentedString(beneficiaryBankCode)).append("\n");
    sb.append("    beneficiaryBranchCode: ").append(toIndentedString(beneficiaryBranchCode)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    beneficiaryName: ").append(toIndentedString(beneficiaryName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
