=begin
#Cards

#The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class MultiCurrencyAccountEligibilityResponse
    # A masked card number that can be displayed to the customer.
    attr_accessor :display_card_number

    # The customer card identifier in encrypted format
    attr_accessor :card_id

    # Flag to identify if the cardNumbre in response is ATM card.
    attr_accessor :atm_card_flag

    # This field is to indicate if the  card is enrolled for Multi Currency Account or not.Please use /v1/apac/utilities/referenceData/{cardEnrollmentStatus} resource to get valid value of this field with description. You can use the field name as the referenceCode parameter to retrieve the values.
    attr_accessor :card_enrollment_status

    # Eligible to add new currency.This is a reference data field. Please use /utilities/referenceData/{ eligibleForCurrencyAddition} resource to get valid value of this field with description.
    attr_accessor :eligible_for_currency_addition

    attr_accessor :account_details

    attr_accessor :currency_details

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'display_card_number' => :'displayCardNumber',
        :'card_id' => :'cardId',
        :'atm_card_flag' => :'atmCardFlag',
        :'card_enrollment_status' => :'cardEnrollmentStatus',
        :'eligible_for_currency_addition' => :'eligibleForCurrencyAddition',
        :'account_details' => :'accountDetails',
        :'currency_details' => :'currencyDetails'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'display_card_number' => :'Object',
        :'card_id' => :'Object',
        :'atm_card_flag' => :'Object',
        :'card_enrollment_status' => :'Object',
        :'eligible_for_currency_addition' => :'Object',
        :'account_details' => :'Object',
        :'currency_details' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SwaggerClient::MultiCurrencyAccountEligibilityResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SwaggerClient::MultiCurrencyAccountEligibilityResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'display_card_number')
        self.display_card_number = attributes[:'display_card_number']
      end

      if attributes.key?(:'card_id')
        self.card_id = attributes[:'card_id']
      end

      if attributes.key?(:'atm_card_flag')
        self.atm_card_flag = attributes[:'atm_card_flag']
      end

      if attributes.key?(:'card_enrollment_status')
        self.card_enrollment_status = attributes[:'card_enrollment_status']
      end

      if attributes.key?(:'eligible_for_currency_addition')
        self.eligible_for_currency_addition = attributes[:'eligible_for_currency_addition']
      end

      if attributes.key?(:'account_details')
        if (value = attributes[:'account_details']).is_a?(Array)
          self.account_details = value
        end
      end

      if attributes.key?(:'currency_details')
        if (value = attributes[:'currency_details']).is_a?(Array)
          self.currency_details = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @display_card_number.nil?
        invalid_properties.push('invalid value for "display_card_number", display_card_number cannot be nil.')
      end

      if @card_id.nil?
        invalid_properties.push('invalid value for "card_id", card_id cannot be nil.')
      end

      if @card_enrollment_status.nil?
        invalid_properties.push('invalid value for "card_enrollment_status", card_enrollment_status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @display_card_number.nil?
      return false if @card_id.nil?
      return false if @card_enrollment_status.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          display_card_number == o.display_card_number &&
          card_id == o.card_id &&
          atm_card_flag == o.atm_card_flag &&
          card_enrollment_status == o.card_enrollment_status &&
          eligible_for_currency_addition == o.eligible_for_currency_addition &&
          account_details == o.account_details &&
          currency_details == o.currency_details
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [display_card_number, card_id, atm_card_flag, card_enrollment_status, eligible_for_currency_addition, account_details, currency_details].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SwaggerClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
