/* 
 * Accounts
 *
 * The Accounts API allows you to retrieve account and transaction data for Citi Customers who have authorized your app. In most cases, you'll want to request a summary of all accounts first, which will return basic account information and accountIds. Once you have this information, you can request additional account details and/or transactions.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EasyPaymentPlansTransactionEligibilityResponse
    /// </summary>
    [DataContract]
        public partial class EasyPaymentPlansTransactionEligibilityResponse :  IEquatable<EasyPaymentPlansTransactionEligibilityResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EasyPaymentPlansTransactionEligibilityResponse" /> class.
        /// </summary>
        /// <param name="easyPaymentPlan">easyPaymentPlan.</param>
        public EasyPaymentPlansTransactionEligibilityResponse(List<EasyPaymentPlan> easyPaymentPlan = default(List<EasyPaymentPlan>))
        {
            this.EasyPaymentPlan = easyPaymentPlan;
        }
        
        /// <summary>
        /// Gets or Sets EasyPaymentPlan
        /// </summary>
        [DataMember(Name="easyPaymentPlan", EmitDefaultValue=false)]
        public List<EasyPaymentPlan> EasyPaymentPlan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EasyPaymentPlansTransactionEligibilityResponse {\n");
            sb.Append("  EasyPaymentPlan: ").Append(EasyPaymentPlan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EasyPaymentPlansTransactionEligibilityResponse);
        }

        /// <summary>
        /// Returns true if EasyPaymentPlansTransactionEligibilityResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EasyPaymentPlansTransactionEligibilityResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EasyPaymentPlansTransactionEligibilityResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EasyPaymentPlan == input.EasyPaymentPlan ||
                    this.EasyPaymentPlan != null &&
                    input.EasyPaymentPlan != null &&
                    this.EasyPaymentPlan.SequenceEqual(input.EasyPaymentPlan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EasyPaymentPlan != null)
                    hashCode = hashCode * 59 + this.EasyPaymentPlan.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
