# coding: utf-8

"""
    Onboarding

    The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApplicantAddKycInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'self_public_figure_declaration_flag': 'bool'
    }

    attribute_map = {
        'self_public_figure_declaration_flag': 'selfPublicFigureDeclarationFlag'
    }

    def __init__(self, self_public_figure_declaration_flag=None):  # noqa: E501
        """ApplicantAddKycInformation - a model defined in Swagger"""  # noqa: E501
        self._self_public_figure_declaration_flag = None
        self.discriminator = None
        if self_public_figure_declaration_flag is not None:
            self.self_public_figure_declaration_flag = self_public_figure_declaration_flag

    @property
    def self_public_figure_declaration_flag(self):
        """Gets the self_public_figure_declaration_flag of this ApplicantAddKycInformation.  # noqa: E501

        Flag for self declaration if applicant is public figure. Valid values: true and false  # noqa: E501

        :return: The self_public_figure_declaration_flag of this ApplicantAddKycInformation.  # noqa: E501
        :rtype: bool
        """
        return self._self_public_figure_declaration_flag

    @self_public_figure_declaration_flag.setter
    def self_public_figure_declaration_flag(self, self_public_figure_declaration_flag):
        """Sets the self_public_figure_declaration_flag of this ApplicantAddKycInformation.

        Flag for self declaration if applicant is public figure. Valid values: true and false  # noqa: E501

        :param self_public_figure_declaration_flag: The self_public_figure_declaration_flag of this ApplicantAddKycInformation.  # noqa: E501
        :type: bool
        """

        self._self_public_figure_declaration_flag = self_public_figure_declaration_flag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicantAddKycInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicantAddKycInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
