/* 
 * Onboarding
 *
 * The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApplicationUpdateConsentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApplicationUpdateConsentDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ApplicationUpdateConsentDetails
        //private ApplicationUpdateConsentDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApplicationUpdateConsentDetails
            //instance = new ApplicationUpdateConsentDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApplicationUpdateConsentDetails
        /// </summary>
        [Test]
        public void ApplicationUpdateConsentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationUpdateConsentDetails
            //Assert.IsInstanceOfType<ApplicationUpdateConsentDetails> (instance, "variable 'instance' is a ApplicationUpdateConsentDetails");
        }


        /// <summary>
        /// Test the property 'ConsentType'
        /// </summary>
        [Test]
        public void ConsentTypeTest()
        {
            // TODO unit test for the property 'ConsentType'
        }
        /// <summary>
        /// Test the property 'IsConsentGiven'
        /// </summary>
        [Test]
        public void IsConsentGivenTest()
        {
            // TODO unit test for the property 'IsConsentGiven'
        }

    }

}
