/* 
 * Cards
 *
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreditCardLimitDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditCardLimitDetailsTests
    {
        // TODO uncomment below to declare an instance variable for CreditCardLimitDetails
        //private CreditCardLimitDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditCardLimitDetails
            //instance = new CreditCardLimitDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditCardLimitDetails
        /// </summary>
        [Test]
        public void CreditCardLimitDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditCardLimitDetails
            //Assert.IsInstanceOfType<CreditCardLimitDetails> (instance, "variable 'instance' is a CreditCardLimitDetails");
        }


        /// <summary>
        /// Test the property 'CurrentContactlessWthoutPinPmtLimit'
        /// </summary>
        [Test]
        public void CurrentContactlessWthoutPinPmtLimitTest()
        {
            // TODO unit test for the property 'CurrentContactlessWthoutPinPmtLimit'
        }
        /// <summary>
        /// Test the property 'PosSpendingLimitAmount'
        /// </summary>
        [Test]
        public void PosSpendingLimitAmountTest()
        {
            // TODO unit test for the property 'PosSpendingLimitAmount'
        }
        /// <summary>
        /// Test the property 'InternetPurchaseLimitAmount'
        /// </summary>
        [Test]
        public void InternetPurchaseLimitAmountTest()
        {
            // TODO unit test for the property 'InternetPurchaseLimitAmount'
        }
        /// <summary>
        /// Test the property 'DailyAtmWithdrawalLimitAmount'
        /// </summary>
        [Test]
        public void DailyAtmWithdrawalLimitAmountTest()
        {
            // TODO unit test for the property 'DailyAtmWithdrawalLimitAmount'
        }
        /// <summary>
        /// Test the property 'DailyTransactionLimitAmount'
        /// </summary>
        [Test]
        public void DailyTransactionLimitAmountTest()
        {
            // TODO unit test for the property 'DailyTransactionLimitAmount'
        }
        /// <summary>
        /// Test the property 'InternetPurchaseActivationFlag'
        /// </summary>
        [Test]
        public void InternetPurchaseActivationFlagTest()
        {
            // TODO unit test for the property 'InternetPurchaseActivationFlag'
        }
        /// <summary>
        /// Test the property 'DomesticTransaction'
        /// </summary>
        [Test]
        public void DomesticTransactionTest()
        {
            // TODO unit test for the property 'DomesticTransaction'
        }
        /// <summary>
        /// Test the property 'InternationalTransaction'
        /// </summary>
        [Test]
        public void InternationalTransactionTest()
        {
            // TODO unit test for the property 'InternationalTransaction'
        }

    }

}
