/* 
 * Cards
 *
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataProductOfferings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataProductOfferingsTests
    {
        // TODO uncomment below to declare an instance variable for DataProductOfferings
        //private DataProductOfferings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataProductOfferings
            //instance = new DataProductOfferings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataProductOfferings
        /// </summary>
        [Test]
        public void DataProductOfferingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataProductOfferings
            //Assert.IsInstanceOfType<DataProductOfferings> (instance, "variable 'instance' is a DataProductOfferings");
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Test]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Remark'
        /// </summary>
        [Test]
        public void RemarkTest()
        {
            // TODO unit test for the property 'Remark'
        }
        /// <summary>
        /// Test the property 'Branding'
        /// </summary>
        [Test]
        public void BrandingTest()
        {
            // TODO unit test for the property 'Branding'
        }
        /// <summary>
        /// Test the property 'TncUrl'
        /// </summary>
        [Test]
        public void TncUrlTest()
        {
            // TODO unit test for the property 'TncUrl'
        }

    }

}
