/* 
 * Cards
 *
 * The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RetrieveCreditChargeCardCorporateCardsCashLimitResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RetrieveCreditChargeCardCorporateCardsCashLimitResponseTests
    {
        // TODO uncomment below to declare an instance variable for RetrieveCreditChargeCardCorporateCardsCashLimitResponse
        //private RetrieveCreditChargeCardCorporateCardsCashLimitResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RetrieveCreditChargeCardCorporateCardsCashLimitResponse
            //instance = new RetrieveCreditChargeCardCorporateCardsCashLimitResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RetrieveCreditChargeCardCorporateCardsCashLimitResponse
        /// </summary>
        [Test]
        public void RetrieveCreditChargeCardCorporateCardsCashLimitResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RetrieveCreditChargeCardCorporateCardsCashLimitResponse
            //Assert.IsInstanceOfType<RetrieveCreditChargeCardCorporateCardsCashLimitResponse> (instance, "variable 'instance' is a RetrieveCreditChargeCardCorporateCardsCashLimitResponse");
        }


        /// <summary>
        /// Test the property 'MaximumDailyCashLimitAmount'
        /// </summary>
        [Test]
        public void MaximumDailyCashLimitAmountTest()
        {
            // TODO unit test for the property 'MaximumDailyCashLimitAmount'
        }
        /// <summary>
        /// Test the property 'MaximumWeeklyCashLimitAmount'
        /// </summary>
        [Test]
        public void MaximumWeeklyCashLimitAmountTest()
        {
            // TODO unit test for the property 'MaximumWeeklyCashLimitAmount'
        }
        /// <summary>
        /// Test the property 'MaximumMonthlyCashLimitAmount'
        /// </summary>
        [Test]
        public void MaximumMonthlyCashLimitAmountTest()
        {
            // TODO unit test for the property 'MaximumMonthlyCashLimitAmount'
        }
        /// <summary>
        /// Test the property 'MaximumIndividualTxnLimitAmount'
        /// </summary>
        [Test]
        public void MaximumIndividualTxnLimitAmountTest()
        {
            // TODO unit test for the property 'MaximumIndividualTxnLimitAmount'
        }

    }

}
