/* 
 * Onboarding
 *
 * The Onboarding API allows you to initiate the basic account opening process for new customers. The resources allow you to present eligible products, send applications for screening and submit a new application for one or more products. The resources also allow you to submit supporting documents. Application status can be checked at any point in the process, with decisioning happening in real time.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ProspectAddRequest
    /// </summary>
    [DataContract]
        public partial class ProspectAddRequest :  IEquatable<ProspectAddRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProspectAddRequest" /> class.
        /// </summary>
        /// <param name="interest">interest (required).</param>
        /// <param name="prospect">prospect (required).</param>
        public ProspectAddRequest(Interest interest = default(Interest), Prospect prospect = default(Prospect))
        {
            // to ensure "interest" is required (not null)
            if (interest == null)
            {
                throw new InvalidDataException("interest is a required property for ProspectAddRequest and cannot be null");
            }
            else
            {
                this.Interest = interest;
            }
            // to ensure "prospect" is required (not null)
            if (prospect == null)
            {
                throw new InvalidDataException("prospect is a required property for ProspectAddRequest and cannot be null");
            }
            else
            {
                this.Prospect = prospect;
            }
        }
        
        /// <summary>
        /// Gets or Sets Interest
        /// </summary>
        [DataMember(Name="interest", EmitDefaultValue=false)]
        public Interest Interest { get; set; }

        /// <summary>
        /// Gets or Sets Prospect
        /// </summary>
        [DataMember(Name="prospect", EmitDefaultValue=false)]
        public Prospect Prospect { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProspectAddRequest {\n");
            sb.Append("  Interest: ").Append(Interest).Append("\n");
            sb.Append("  Prospect: ").Append(Prospect).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProspectAddRequest);
        }

        /// <summary>
        /// Returns true if ProspectAddRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ProspectAddRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProspectAddRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Interest == input.Interest ||
                    (this.Interest != null &&
                    this.Interest.Equals(input.Interest))
                ) && 
                (
                    this.Prospect == input.Prospect ||
                    (this.Prospect != null &&
                    this.Prospect.Equals(input.Prospect))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Interest != null)
                    hashCode = hashCode * 59 + this.Interest.GetHashCode();
                if (this.Prospect != null)
                    hashCode = hashCode * 59 + this.Prospect.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
