# coding: utf-8

"""
    Cards

    The Cards API allows you to perform actions on the actual credit cards of the Citi Customer who authorized your app.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.retrieve_credit_charge_card_fulfillment_arrangement_credit_plan_loans_response import RetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestRetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse(unittest.TestCase):
    """RetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse(self):
        """Test RetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.retrieve_credit_charge_card_fulfillment_arrangement_credit_plan_loans_response.RetrieveCreditChargeCardFulfillmentArrangementCreditPlanLoansResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
